# Generated by Django 4.2.7 on 2023-12-05 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_today', models.DateField(auto_now_add=True)),
                ('checkin', models.TimeField(blank=True, null=True)),
                ('checkin_desc', models.TextField(blank=True)),
                ('checkout', models.TimeField(blank=True, null=True)),
                ('checkout_desc', models.TextField(blank=True)),
                ('hours', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
